name: ci
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    name: Run normal tests
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
      RUST_BACKTRACE: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          components: clippy
          toolchain: stable
          override: true
      - name: test
        run: cargo test
      - name: clippy
        run: clippy check
  miri:
    name: Run fmt & miri
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
      RUST_BACKTRACE: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          components: miri,rustfmt
          toolchain: nightly
          override: true
      - name: format lint
        run: cargo fmt --check --all
      - name: miri setup
        run: cargo miri setup
      - name: miri test
        run: cargo miri run
